

(add-to-list 'load-path (locate-user-emacs-file "modules"))
(require 'mk-straight)
(require 'mk-base)
(require 'mk-view)
(require 'mk-git)
;;(require 'mk-path-from-shell)
;; (require 'mk-engine-mode)
;; (require 'mk-which-key)

;; (require 'mk-eshell)
;; (require 'mk-vterm)
;; (require 'mk-ghostel)
;; (require 'mk-kitty-graphics)
;; (require 'mk-claude-code-ide)
;; (require 'mk-claude-code)
;; (require 'mk-ai-code-interface)
;; (require 'mk-dirvish)
;; (require 'mk-org)
;; (require 'mk-markdown)
;; (require 'mk-org-scratch)
;; (require 'mk-keybind)
;; (require 'mk-lsp)
;; (require 'mk-language-mode)
;; (require 'mk-rails)
;; (require 'mk-origami)
;; (require 'mk-multiple-cursors)
