(add-to-list 'load-path (locate-user-emacs-file "modules"))
(require 'mk-straight)
(require 'mk-base)
(require 'mk-keybind)
(require 'mk-drill-instructor)
(require 'mk-skk)
(require 'mk-view)
(require 'mk-git)
(require 'mk-dirvish)
(require 'mk-shell)
(require 'mk-vterm)
(require 'mk-ghostel)
(require 'mk-claude-code-ide)
(require 'mk-claude-code)
(require 'mk-path-from-shell)
(require 'mk-engine-mode)
(require 'mk-which-key)
(require 'mk-ai-code-interface)
(require 'mk-org)
(require 'mk-org-scratch)
(require 'mk-markdown)
(require 'mk-treesit)
(require 'mk-lsp)
(require 'mk-lsp-manager)
(require 'mk-language-mode)
(require 'mk-rails)
(require 'mk-origami)
(require 'mk-multiple-cursors)

(defun my/herdr (&optional new)
  "herdr 専用の Ghostel バッファを開く。
既に動いていればそこに切り替える。
NEW が非 nil なら常に新しいバッファを作る。"
  (interactive "P")
  (let* ((name "*herdr*")
         (buf (and (not new) (get-buffer name))))
    (unless (buffer-live-p buf)
      (setq buf (generate-new-buffer (if new (generate-new-buffer-name name) name)))
      (condition-case err
          (ghostel-exec buf "herdr")
        (error (kill-buffer buf) (signal (car err) (cdr err)))))
    (pop-to-buffer buf)))
